#!/usr/bin/env python3
"""
Generates assets/dark_mode.svg and assets/light_mode.svg.

The ASCII portrait is read verbatim from assets/ascii-portrait-dark.txt /
-light.txt (exact character-grid exports, not regenerated by this script).

The SVG opens with a typewriter intro — "nathan@bijo:~$ " followed by
"neofetch" typed character-by-character with a blinking cursor — before
the actual card fades in. This is pure SMIL (<animate>/<set>), no JS, so
it survives GitHub's markdown sanitizer the same way projects like
readme-typing-svg do. It replays from the start on every page load, since
that's just what happens when a browser reloads an <img>.

Run locally:   python3 scripts/generate_neofetch.py --theme dark
In CI:         python3 scripts/generate_neofetch.py --theme dark --live
"""
import argparse
import os
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
GITHUB_USER = "Nathanbijo"

ART_FILES = {
    "dark": ROOT / "assets" / "ascii-portrait-dark.txt",
    "light": ROOT / "assets" / "ascii-portrait-light.txt",
}

# ---------------------------------------------------------------------------
# Static content
#
# A row is one of:
#   None                    -> blank spacer line
#   (label, value)           -> single "label: value" line
#   [(label, value), (l,v)]  -> compact line, "label: value | label: value"
#     (list, not tuple — that's what distinguishes it from a single row)
# ---------------------------------------------------------------------------
FIELDS = [
    ("nathan@bijo", [
        ("OS", "Fedora Linux, Windows, Android"),
        ("Uptime", "{{UPTIME}}"),
        ("Host", "STEAG Energy Services"),
        ("Kernel", "Simulation Software Engineering Intern"),
        ("IDE", "VS Code, Antigravity"),
        None,
        ("Languages.Programming", "Python, JavaScript, SQL, C, C++"),
        ("Languages.Computer", "HTML, CSS, JSON, LaTeX, YAML"),
        ("Languages.Real", "English, Malayalam, Hindi"),
        ("Backend", "FastAPI, Express, PostgreSQL, Docker"),
        None,
        ("Projects.WARESYS", "OCR invoice-to-inventory, patent published"),
        ("Projects.MarketFlow", "URL to branded posts via Llama 3"),
        ("Projects.Padosi", "Kochi liveability + knowledge map [WIP]"),
    ]),
    ("- Contact", [
        ("Email.Personal", "nathan.bijo@gmail.com"),
        ("LinkedIn", "nathan-bijo"),
        ("Portfolio", "nathanbijo.dev"),
    ]),
    ("- GitHub Stats", [
        ("Repos", "{{REPOS}}"),
        ("Commits", "{{COMMITS}}"),
        ("Lines of Code on GitHub", [
            ("{{LOC}}", "value"), (" ( ", "cc"),
            ("{{LOC_ADD}}++", "addColor"), (", ", "cc"),
            ("{{LOC_DEL}}--", "delColor"), (" )", "cc"),
        ]),
    ]),
]

PLACEHOLDER_STATS = {
    "REPOS": "\u2014", "CONTRIB": "\u2014", "COMMITS": "\u2014",
    "LOC": "\u2014", "LOC_ADD": "0", "LOC_DEL": "0",
    "UPTIME": "\u2014 (set START_DATE below)",
}
STAT_KEYS = ("REPOS", "CONTRIB", "COMMITS", "LOC", "LOC_ADD", "LOC_DEL", "UPTIME")
START_DATE = "2006-01-04"  # e.g. "2022-07-01" — decide what "Uptime" measures for you

# Colors taken literally from the two HTML exports — not restyled.
THEMES = {
    "dark": dict(bg="#000000", art="#ffffff", key="#ffa657", value="#a5d6ff",
                 cc="#8b949e", add="#3fb950", delc="#f85149"),
    "light": dict(bg="#ffffff", art="#000000", key="#9a6700", value="#0550ae",
                  cc="#57606a", add="#1a7f37", delc="#cf222e"),
}

# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------
FONT_SIZE = 16
CHAR_W = 8.5   # measured off the reference repo's own layout at font-size 16
LINE_H = 20
ART_X = 15
TOP = 30
GAP = 20            # gutter between art column and stats column
RIGHT_PAD = 25
COL_PAD = 3         # min dots after the longest single-value line
SEP = " | "         # separator between the two halves of a compact line

# The ASCII portrait is rendered at a smaller font size than the info column
# so the two columns end up the same visual height. This scales the *type*,
# not the character grid — the .txt art is untouched and keeps every bit of
# its detail, since SVG text is vector. Resampling the grid to fewer columns
# would instead throw away portrait detail permanently.
#
# None = derive it automatically so art height == stats height. Set a float
# (e.g. 0.8) to override if you want the portrait deliberately larger or
# smaller than the info block.
ART_SCALE = None
ART_SCALE_MIN = 0.45   # floor: below this the portrait stops being legible

# ---------------------------------------------------------------------------
# Typewriter intro
# ---------------------------------------------------------------------------
INTRO_CMD = "neofetch"
CHAR_DELAY = 0.11   # seconds per typed character
TYPE_START = 0.4    # pause before typing starts
ENTER_PAUSE = 0.35  # pause after last char, before the card fades in
FADE_DUR = 0.5


def compute_uptime():
    if not START_DATE:
        return PLACEHOLDER_STATS["UPTIME"]
    from datetime import date
    y, m, d = map(int, START_DATE.split("-"))
    start = date(y, m, d)
    today = date.today()
    years = today.year - start.year - ((today.month, today.day) < (start.month, start.day))
    months = (today.month - start.month) % 12
    days = (today - date(today.year, today.month, min(start.day, 28))).days % 30
    return f"{years} years, {months} months, {days} days"


EXCLUDE_DIRS = {"node_modules", "dist", "build", "vendor", "__pycache__",
                 ".venv", "venv", ".next", "target", "bin", "obj", ".git"}
EXCLUDE_FILES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml",
                  "poetry.lock", "Pipfile.lock", "Cargo.lock"}


def _github_get(url, headers):
    import json
    import urllib.request
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.load(r)


def _github_graphql(query, variables, headers):
    import json
    import urllib.request
    req = urllib.request.Request(
        "https://api.github.com/graphql",
        data=json.dumps({"query": query, "variables": variables}).encode(),
        headers={**headers, "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.load(r)


def _commits_and_contributed(token, headers):
    """totalCommitContributions / totalRepositoriesWithContributedCommits are
    both scoped to the query's from/to range, capped at 1 year by GitHub —
    there's no single query for an all-time total. Loop year by year from
    account creation, summing commits and collecting distinct repo names
    (summing repo counts directly would double-count a repo touched in
    multiple years)."""
    import datetime

    if not token:
        print("::warning::commits/contributed skipped — no GH_PAT token", file=sys.stderr)
        return None, None
    try:
        user = _github_get(f"https://api.github.com/users/{GITHUB_USER}", headers)
        start_year = int(user["created_at"][:4])
    except Exception as e:
        print(f"::warning::commits/contributed: couldn't fetch user info: {e!r}", file=sys.stderr)
        return None, None

    query = """
    query($login:String!, $from:DateTime!, $to:DateTime!) {
      user(login:$login) {
        contributionsCollection(from:$from, to:$to) {
          totalCommitContributions
          commitContributionsByRepository(maxRepositories:100) {
            repository { nameWithOwner }
          }
        }
      }
    }"""
    total_commits = 0
    contributed = set()
    this_year = datetime.date.today().year
    for year in range(start_year, this_year + 1):
        frm = f"{year}-01-01T00:00:00Z"
        to = (f"{year}-12-31T23:59:59Z" if year < this_year
              else datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"))
        try:
            data = _github_graphql(query, {"login": GITHUB_USER, "from": frm, "to": to}, headers)
            if "errors" in data:
                print(f"::warning::commits/contributed GraphQL error for {year}: {data['errors']}", file=sys.stderr)
                continue
            cc = data["data"]["user"]["contributionsCollection"]
            total_commits += cc["totalCommitContributions"]
            for node in cc["commitContributionsByRepository"]:
                contributed.add(node["repository"]["nameWithOwner"])
        except Exception as e:
            print(f"::warning::commits/contributed failed for {year}: {e!r}", file=sys.stderr)
            continue
    return total_commits, len(contributed)


def _lines_of_code(repos, token, user_info):
    """Clone each owned, non-fork repo and sum `git log --numstat`, filtered
    to this author's commits. Vendored/generated paths (node_modules, lock
    files, build output, ...) are excluded — verified against a real repo
    during development: one accidentally-committed node_modules turned a
    true ~5k-line contribution into a fake 589k. Public repos clone without
    a token; a token is only needed to also include private ones."""
    import re as _re
    import subprocess
    import tempfile

    emails = {"nathan.bijo@gmail.com"}
    if user_info.get("id"):
        emails.add(f"{user_info['id']}+{GITHUB_USER}@users.noreply.github.com")
    if user_info.get("email"):
        emails.add(user_info["email"])
    author_pattern = "|".join(_re.escape(e) for e in emails)

    add_total = del_total = 0
    with tempfile.TemporaryDirectory() as tmp:
        for repo in repos:
            if repo.get("fork"):
                continue
            url = repo["clone_url"]
            if token:
                url = url.replace("https://", f"https://{token}@")
            dest = os.path.join(tmp, repo["name"])
            try:
                subprocess.run(
                    ["git", "clone", "--quiet", "--no-tags", url, dest],
                    check=True, timeout=180,
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
                out = subprocess.run(
                    ["git", "-C", dest, "log", f"--author={author_pattern}",
                     "--perl-regexp", "--pretty=tformat:", "--numstat"],
                    check=True, timeout=90, capture_output=True, text=True,
                ).stdout
            except Exception as e:
                print(f"::warning::LOC skip {repo['name']}: {e!r}", file=sys.stderr)
                continue
            for line in out.splitlines():
                parts = line.split("\t")
                if len(parts) != 3 or not parts[0].isdigit() or not parts[1].isdigit():
                    continue  # binary files report "-" for both counts
                path_parts = parts[2].split("/")
                if any(d in EXCLUDE_DIRS for d in path_parts) or path_parts[-1] in EXCLUDE_FILES:
                    continue
                add_total += int(parts[0])
                del_total += int(parts[1])
    return add_total, del_total


def fetch_live_stats(token=None):
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    user = _github_get(f"https://api.github.com/users/{GITHUB_USER}", headers)
    repos = _github_get(f"https://api.github.com/users/{GITHUB_USER}/repos?per_page=100", headers)
    repos = repos if isinstance(repos, list) else []

    stats = dict(PLACEHOLDER_STATS)
    stats["REPOS"] = str(user.get("public_repos", "\u2014"))

    commits, contributed = _commits_and_contributed(token, headers)
    if commits is not None:
        stats["COMMITS"] = f"{commits:,}"
        stats["CONTRIB"] = str(contributed)

    add_total, del_total = _lines_of_code(repos, token, user)
    stats["LOC"] = f"{add_total - del_total:,}"
    stats["LOC_ADD"] = f"{add_total:,}"
    stats["LOC_DEL"] = f"{del_total:,}"

    return stats


def _resolve(value, stats):
    """value is either a plain string, or a list of (text, css_class) segments
    for rows that need multiple colors (e.g. the LOC row's green ++ / red --).
    Placeholder substitution happens either way; the return type matches input."""
    def sub(text):
        for k in STAT_KEYS:
            text = text.replace("{{%s}}" % k, stats[k])
        return text

    if isinstance(value, list):
        return [(sub(text), cls) for text, cls in value]
    return sub(value)


def _value_len(value):
    if isinstance(value, list):
        return sum(len(text) for text, _ in value)
    return len(value)


def _iter_single_rows(stats):
    """Yield (label, resolved_value) for every plain row across all sections —
    used to size the stats column to actual content instead of a guess."""
    for _, rows in FIELDS:
        for row in rows:
            if isinstance(row, tuple):
                label, value = row
                yield label, _resolve(value, stats)


def compute_stats_cols(stats):
    """Card width (in characters) is driven by content, not a fixed guess —
    the longest single-value line plus a little breathing room."""
    longest = max(
        (len(label) + 1 + _value_len(value) + 2 for label, value in _iter_single_rows(stats)),
        default=40,
    )
    return longest + COL_PAD


def dotted(label, value_len, width):
    used = len(label) + 1 + value_len + 2
    n = max(1, width - used)
    return " " + "." * n + " "


def check_overflow(stats, stats_cols):
    problems = []
    for label, value in _iter_single_rows(stats):
        used = len(label) + 1 + _value_len(value) + 2
        if used > stats_cols:
            problems.append(f"{label!r} -> {used}/{stats_cols} cols")
    if problems:
        raise ValueError("Field(s) overflow the stats column:\n  " + "\n  ".join(problems))


def _emit_segments(p, cx, y, segs):
    """Every segment is a SIBLING tspan with its own explicit x and its own
    textLength — never nested inside another textLength-controlled tspan,
    since nested textLength isn't reliably honored across renderers."""
    for text, cls, chars in segs:
        if not text:
            continue
        w = chars * CHAR_W
        cls_attr = f' class="{cls}"' if cls else ""
        p.append(
            f'<tspan x="{cx:.1f}" y="{y:.1f}"{cls_attr} '
            f'textLength="{w:.1f}" lengthAdjust="spacingAndGlyphs">{escape(text)}</tspan>'
        )
        cx += w
    return cx


def _label_segments(label):
    segs = []
    for i, part in enumerate(label.split(".")):
        if i:
            segs.append((".", "key", 1))
        segs.append((part, "key", len(part)))
    return segs


def build(theme_name, stats):
    theme = THEMES[theme_name]
    art_lines = ART_FILES[theme_name].read_text().split("\n")
    art_cols = max(len(l) for l in art_lines)
    art_rows = len(art_lines)

    stats_cols = compute_stats_cols(stats)
    half_cols = (stats_cols - len(SEP)) // 2
    stats_rows = sum(len(rows) + 1 for _, rows in FIELDS) + len(FIELDS)

    # Scale the portrait's type so its rendered height matches the info column.
    scale = ART_SCALE if ART_SCALE is not None else stats_rows / art_rows
    scale = max(ART_SCALE_MIN, min(1.0, scale))
    art_font = FONT_SIZE * scale
    art_char_w = CHAR_W * scale
    art_line_h = LINE_H * scale

    col_x = ART_X + art_cols * art_char_w + GAP

    width = int(col_x + stats_cols * CHAR_W + RIGHT_PAD)
    art_h = art_rows * art_line_h
    stats_h = stats_rows * LINE_H
    body_h = max(art_h, stats_h)
    # +1 row at the top for the typed "neofetch" command line.
    height = int(TOP + LINE_H + body_h + 20)

    top_card = TOP + LINE_H  # everything that used to start at TOP shifts down one row
    # Center the shorter column against the taller one so neither floats.
    art_top = top_card + max(0, (body_h - art_h) / 2)
    stats_top = top_card + max(0, (body_h - stats_h) / 2)

    font_stack = (
        "ConsolasFallback,Consolas,Menlo,'DejaVu Sans Mono',"
        "'Liberation Mono','Courier New',monospace"
    )

    p = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="0 0 {width} {height}" width="{width}" height="{height}" '
        f'font-family="{font_stack}" font-size="{FONT_SIZE}px">',
        f"""<style>
@font-face {{
src: local('Consolas'), local('Consolas Bold');
font-family: 'ConsolasFallback';
font-display: swap;
-webkit-size-adjust: 109%;
size-adjust: 109%;
}}
.key {{fill: {theme['key']};}}
.value {{fill: {theme['value']};}}
.addColor {{fill: {theme['add']};}}
.delColor {{fill: {theme['delc']};}}
.cc {{fill: {theme['cc']};}}
text, tspan {{white-space: pre;}}
</style>""",
        f'<rect width="{width}" height="{height}" fill="{theme["bg"]}" rx="15"/>',
    ]

    # ---- Typewriter intro: "nathan@bijo:~$ neofetch" + blinking cursor ----
    # The typed command is ONE static, fully-opaque text run — visibility is
    # controlled by a clip-path rect growing in discrete steps, not by
    # toggling opacity on individual <tspan> characters. That per-character
    # approach was tested and dropped: at least one real SVG renderer
    # (resvg) silently ignores `opacity` set on <tspan>, confirmed by
    # inspecting the raw output bytes, not just eyeballing a render. A
    # clip-path's rect `width` is a basic numeric attribute animation with
    # no such ambiguity, so the reveal can't silently fail to hide text.
    prompt = FIELDS[0][0] + ":~$ "
    p.append(f'<text x="{ART_X}" y="{TOP}" fill="{theme["art"]}" font-size="{FONT_SIZE}px">')
    cx = _emit_segments(p, ART_X, TOP, [(prompt, None, len(prompt))])
    cmd_start_x = cx
    cmd_width = len(INTRO_CMD) * CHAR_W
    p.append("</text>")

    type_dur = len(INTRO_CMD) * CHAR_DELAY
    step_widths = [i * CHAR_W for i in range(len(INTRO_CMD) + 1)]
    key_times = [i / len(INTRO_CMD) for i in range(len(INTRO_CMD) + 1)]
    clip_id = f"typeClip-{theme_name}"
    p.append(
        f'<clipPath id="{clip_id}"><rect x="{cmd_start_x:.1f}" y="{TOP - FONT_SIZE}" '
        f'width="0" height="{FONT_SIZE + 6}">'
        f'<animate attributeName="width" begin="{TYPE_START:.2f}s" dur="{type_dur:.2f}s" '
        f'calcMode="discrete" fill="freeze" '
        f'keyTimes="{";".join(f"{k:.4f}" for k in key_times)}" '
        f'values="{";".join(f"{v:.1f}" for v in step_widths)}"/>'
        f'</rect></clipPath>'
    )
    p.append(f'<g clip-path="url(#{clip_id})">')
    p.append(
        f'<text x="{cmd_start_x:.1f}" y="{TOP}" fill="{theme["art"]}" font-size="{FONT_SIZE}px">'
        f'<tspan x="{cmd_start_x:.1f}" y="{TOP}" textLength="{cmd_width:.1f}" '
        f'lengthAdjust="spacingAndGlyphs">{escape(INTRO_CMD)}</tspan></text>'
    )
    p.append("</g>")

    type_end = TYPE_START + type_dur
    reveal_start = type_end + ENTER_PAUSE
    cursor_positions = [cmd_start_x + w for w in step_widths]
    p.append(
        f'<rect x="{cursor_positions[0]:.1f}" y="{TOP - FONT_SIZE + 2}" '
        f'width="{CHAR_W - 1:.1f}" height="{FONT_SIZE + 2}" fill="{theme["art"]}">'
        f'<animate attributeName="x" begin="{TYPE_START:.2f}s" dur="{type_dur:.2f}s" '
        f'calcMode="discrete" fill="freeze" '
        f'keyTimes="{";".join(f"{k:.4f}" for k in key_times)}" '
        f'values="{";".join(f"{v:.1f}" for v in cursor_positions)}"/>'
        f'<animate attributeName="opacity" values="1;1;0;0" keyTimes="0;0.5;0.5;1" '
        f'dur="0.9s" repeatCount="indefinite" begin="0s"/>'
        f'<set attributeName="display" to="none" begin="{reveal_start:.2f}s" fill="freeze"/>'
        f'</rect>'
    )

    # ---- Card content, hidden until the "Enter" pause finishes ----
    p.append(f'<g opacity="0">')
    p.append(
        f'<animate attributeName="opacity" from="0" to="1" '
        f'begin="{reveal_start:.2f}s" dur="{FADE_DUR}s" fill="freeze"/>'
    )

    p.append(f'<text x="{ART_X}" y="{art_top:.1f}" fill="{theme["art"]}" font-size="{art_font:.2f}px" class="ascii">')
    for i, line in enumerate(art_lines):
        tl = len(line) * art_char_w
        p.append(
            f'<tspan x="{ART_X}" y="{art_top + i * art_line_h:.1f}" '
            f'textLength="{tl:.1f}" lengthAdjust="spacingAndGlyphs">{escape(line)}</tspan>'
        )
    p.append("</text>")

    p.append(f'<text x="{col_x}" y="{stats_top:.1f}" fill="{theme["art"]}" font-size="{FONT_SIZE}px">')
    y = stats_top
    for header, rows in FIELDS:
        rule = "-" + "\u2014" * 44 + "-\u2014-"
        header_tl = len(header) * CHAR_W
        p.append(
            f'<tspan x="{col_x:.1f}" y="{y:.1f}" textLength="{header_tl:.1f}" '
            f'lengthAdjust="spacingAndGlyphs">{escape(header)}</tspan> {rule}'
        )
        y += LINE_H
        for row in rows:
            if row is None:
                p.append(f'<tspan x="{col_x:.1f}" y="{y:.1f}" class="cc">. </tspan>')
                y += LINE_H
                continue

            if isinstance(row, list):
                # Compact line: ". label1: ...dots... value1 | label2: ...dots... value2"
                cx = col_x
                cx = _emit_segments(p, cx, y, [(". ", "cc", 2)])
                for j, (label, value) in enumerate(row):
                    value = _resolve(value, stats)
                    fill = dotted(label, len(value), half_cols)
                    segs = _label_segments(label) + [
                        (":", "cc", 1), (fill, "cc", len(fill)), (value, "value", len(value)),
                    ]
                    cx = _emit_segments(p, cx, y, segs)
                    if j == 0:
                        cx = _emit_segments(p, cx, y, [(SEP, "cc", len(SEP))])
                y += LINE_H
                continue

            label, value = row
            value = _resolve(value, stats)
            if isinstance(value, list):
                # Multi-color value — e.g. LOC row: net figure + green ++ / red --
                fill = dotted(label, _value_len(value), stats_cols)
                segs = (
                    [(". ", "cc", 2)] + _label_segments(label)
                    + [(":", "cc", 1), (fill, "cc", len(fill))]
                    + [(text, cls, len(text)) for text, cls in value]
                )
            else:
                fill = dotted(label, len(value), stats_cols)
                segs = (
                    [(". ", "cc", 2)] + _label_segments(label)
                    + [(":", "cc", 1), (fill, "cc", len(fill)), (value, "value", len(value))]
                )
            _emit_segments(p, col_x, y, segs)
            y += LINE_H
        y += LINE_H
    p.append("</text>")
    p.append("</g>")
    p.append("</svg>")
    return "\n".join(p), width, height


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--theme", choices=["dark", "light", "both"], default="both")
    ap.add_argument("--live", action="store_true")
    args = ap.parse_args()

    stats = dict(PLACEHOLDER_STATS)
    stats["UPTIME"] = compute_uptime()
    if args.live:
        stats.update(fetch_live_stats(os.environ.get("GH_PAT")))

    check_overflow(stats, compute_stats_cols(stats))

    themes = ["dark", "light"] if args.theme == "both" else [args.theme]
    out_dir = ROOT / "assets"
    out_dir.mkdir(exist_ok=True)
    for t in themes:
        svg, w, h = build(t, stats)
        out_path = out_dir / f"{t}_mode.svg"
        out_path.write_text(svg)
        print(f"wrote {out_path}  ({w}x{h})")


if __name__ == "__main__":
    main()
