#!/usr/bin/env python3
"""
Generates assets/dark_mode.svg and assets/light_mode.svg.

The ASCII portrait is read verbatim from assets/ascii-portrait-dark.txt /
-light.txt (exact character-grid exports, not regenerated by this script).

The SVG opens with a typewriter intro — "nathan@bijo:~$ " followed by
"neofetch" typed character-by-character with a blinking cursor — before
the actual card fades in. This is pure SMIL (<animate>/<set>), no JS, so
it survives GitHub's markdown sanitizer the same way projects like
readme-typing-svg do. It replays from the start on every page load, since
that's just what happens when a browser reloads an <img>.

Run locally:   python3 scripts/generate_neofetch.py --theme dark
In CI:         python3 scripts/generate_neofetch.py --theme dark --live
"""
import argparse
import os
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
GITHUB_USER = "Nathanbijo"

ART_FILES = {
    "dark": ROOT / "assets" / "ascii-portrait-dark.txt",
    "light": ROOT / "assets" / "ascii-portrait-light.txt",
}

# ---------------------------------------------------------------------------
# Static content
#
# A row is one of:
#   None                    -> blank spacer line
#   (label, value)           -> single "label: value" line
#   [(label, value), (l,v)]  -> compact line, "label: value | label: value"
#     (list, not tuple — that's what distinguishes it from a single row)
# ---------------------------------------------------------------------------
FIELDS = [
    ("nathan@bijo", [
        ("OS", "Fedora Linux, Android"),
        ("Uptime", "{{UPTIME}}"),
        ("Host", "STEAG Energy Services"),
        ("Kernel", "Simulation Software Engineering Intern"),
        ("IDE", "VS Code, Neovim"),
        None,
        ("Languages.Programming", "Python, TypeScript, Java, SQL"),
        ("Languages.Computer", "HTML, CSS, JSON, LaTeX, YAML"),
        ("Languages.Real", "English, Malayalam, Hindi"),
        None,
        ("Projects.WARESYS", "OCR invoice pipeline, 95% accuracy"),
        ("Projects.MarketFlow", "URL to branded social posts"),
        ("Projects.Padosi", "Neighbourhood ranking [WIP]"),
        None,
        ("Honors", "Cryptography, Neurobots Finalist @ IIT Palakkad"),
    ]),
    ("- Contact", [
        ("Email.Personal", "nathan.bijo@gmail.com"),
        ("LinkedIn", "nathan-bijo"),
        ("GitHub", GITHUB_USER),
        ("Portfolio", "nathanbijo.dev"),
    ]),
    ("- GitHub Stats", [
        [("Repos", "{{REPOS}}"), ("Stars", "{{STARS}}")],
        [("Commits", "{{COMMITS}}"), ("Followers", "{{FOLLOWERS}}")],
    ]),
]

PLACEHOLDER_STATS = {
    "REPOS": "\u2014", "STARS": "\u2014", "COMMITS": "\u2014", "FOLLOWERS": "\u2014",
    "UPTIME": "\u2014 (set START_DATE below)",
}
START_DATE = None  # e.g. "2022-07-01" — decide what "Uptime" measures for you

# Colors taken literally from the two HTML exports — not restyled.
THEMES = {
    "dark": dict(bg="#000000", art="#ffffff", key="#ffa657", value="#a5d6ff",
                 cc="#8b949e", add="#3fb950", delc="#f85149"),
    "light": dict(bg="#ffffff", art="#000000", key="#9a6700", value="#0550ae",
                  cc="#57606a", add="#1a7f37", delc="#cf222e"),
}

# ---------------------------------------------------------------------------
# Geometry
# ---------------------------------------------------------------------------
FONT_SIZE = 16
CHAR_W = 8.5   # measured off the reference repo's own layout at font-size 16
LINE_H = 20
ART_X = 15
TOP = 30
GAP = 20            # gutter between art column and stats column
RIGHT_PAD = 25
COL_PAD = 3         # min dots after the longest single-value line
SEP = " | "         # separator between the two halves of a compact line

# The ASCII portrait is rendered at a smaller font size than the info column
# so the two columns end up the same visual height. This scales the *type*,
# not the character grid — the .txt art is untouched and keeps every bit of
# its detail, since SVG text is vector. Resampling the grid to fewer columns
# would instead throw away portrait detail permanently.
#
# None = derive it automatically so art height == stats height. Set a float
# (e.g. 0.8) to override if you want the portrait deliberately larger or
# smaller than the info block.
ART_SCALE = None
ART_SCALE_MIN = 0.45   # floor: below this the portrait stops being legible

# ---------------------------------------------------------------------------
# Typewriter intro
# ---------------------------------------------------------------------------
INTRO_CMD = "neofetch"
CHAR_DELAY = 0.11   # seconds per typed character
TYPE_START = 0.4    # pause before typing starts
ENTER_PAUSE = 0.35  # pause after last char, before the card fades in
FADE_DUR = 0.5


def compute_uptime():
    if not START_DATE:
        return PLACEHOLDER_STATS["UPTIME"]
    from datetime import date
    y, m, d = map(int, START_DATE.split("-"))
    start = date(y, m, d)
    today = date.today()
    years = today.year - start.year - ((today.month, today.day) < (start.month, start.day))
    months = (today.month - start.month) % 12
    days = (today - date(today.year, today.month, min(start.day, 28))).days % 30
    return f"{years} years, {months} months, {days} days"


def fetch_live_stats(token=None):
    import json
    import urllib.request
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    def get(url):
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.load(r)

    user = get(f"https://api.github.com/users/{GITHUB_USER}")
    repos = get(f"https://api.github.com/users/{GITHUB_USER}/repos?per_page=100")
    stars = sum(r.get("stargazers_count", 0) for r in repos) if isinstance(repos, list) else 0
    return {
        "REPOS": str(user.get("public_repos", "\u2014")),
        "STARS": str(stars),
        "FOLLOWERS": str(user.get("followers", "\u2014")),
        "COMMITS": PLACEHOLDER_STATS["COMMITS"],  # needs GraphQL + PAT
    }


def _resolve(value, stats):
    for k in ("REPOS", "STARS", "COMMITS", "FOLLOWERS", "UPTIME"):
        value = value.replace("{{%s}}" % k, stats[k])
    return value


def _iter_single_rows(stats):
    """Yield (label, value) for every plain row across all sections —
    used to size the stats column to actual content instead of a guess."""
    for _, rows in FIELDS:
        for row in rows:
            if isinstance(row, tuple):
                label, value = row
                yield label, _resolve(value, stats)


def compute_stats_cols(stats):
    """Card width (in characters) is driven by content, not a fixed guess —
    the longest single-value line plus a little breathing room."""
    longest = max(
        (len(label) + 1 + len(value) + 2 for label, value in _iter_single_rows(stats)),
        default=40,
    )
    return longest + COL_PAD


def dotted(label, value, width):
    used = len(label) + 1 + len(value) + 2
    n = max(1, width - used)
    return " " + "." * n + " "


def check_overflow(stats, stats_cols):
    problems = []
    for label, value in _iter_single_rows(stats):
        used = len(label) + 1 + len(value) + 2
        if used > stats_cols:
            problems.append(f"{label!r} -> {used}/{stats_cols} cols")
    if problems:
        raise ValueError("Field(s) overflow the stats column:\n  " + "\n  ".join(problems))


def _emit_segments(p, cx, y, segs):
    """Every segment is a SIBLING tspan with its own explicit x and its own
    textLength — never nested inside another textLength-controlled tspan,
    since nested textLength isn't reliably honored across renderers."""
    for text, cls, chars in segs:
        if not text:
            continue
        w = chars * CHAR_W
        cls_attr = f' class="{cls}"' if cls else ""
        p.append(
            f'<tspan x="{cx:.1f}" y="{y:.1f}"{cls_attr} '
            f'textLength="{w:.1f}" lengthAdjust="spacingAndGlyphs">{escape(text)}</tspan>'
        )
        cx += w
    return cx


def _label_segments(label):
    segs = []
    for i, part in enumerate(label.split(".")):
        if i:
            segs.append((".", "key", 1))
        segs.append((part, "key", len(part)))
    return segs


def build(theme_name, stats):
    theme = THEMES[theme_name]
    art_lines = ART_FILES[theme_name].read_text().split("\n")
    art_cols = max(len(l) for l in art_lines)
    art_rows = len(art_lines)

    stats_cols = compute_stats_cols(stats)
    half_cols = (stats_cols - len(SEP)) // 2
    stats_rows = sum(len(rows) + 1 for _, rows in FIELDS) + len(FIELDS)

    # Scale the portrait's type so its rendered height matches the info column.
    scale = ART_SCALE if ART_SCALE is not None else stats_rows / art_rows
    scale = max(ART_SCALE_MIN, min(1.0, scale))
    art_font = FONT_SIZE * scale
    art_char_w = CHAR_W * scale
    art_line_h = LINE_H * scale

    col_x = ART_X + art_cols * art_char_w + GAP

    width = int(col_x + stats_cols * CHAR_W + RIGHT_PAD)
    art_h = art_rows * art_line_h
    stats_h = stats_rows * LINE_H
    body_h = max(art_h, stats_h)
    # +1 row at the top for the typed "neofetch" command line.
    height = int(TOP + LINE_H + body_h + 20)

    top_card = TOP + LINE_H  # everything that used to start at TOP shifts down one row
    # Center the shorter column against the taller one so neither floats.
    art_top = top_card + max(0, (body_h - art_h) / 2)
    stats_top = top_card + max(0, (body_h - stats_h) / 2)

    font_stack = (
        "ConsolasFallback,Consolas,Menlo,'DejaVu Sans Mono',"
        "'Liberation Mono','Courier New',monospace"
    )

    p = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="0 0 {width} {height}" width="{width}" height="{height}" '
        f'font-family="{font_stack}" font-size="{FONT_SIZE}px">',
        f"""<style>
@font-face {{
src: local('Consolas'), local('Consolas Bold');
font-family: 'ConsolasFallback';
font-display: swap;
-webkit-size-adjust: 109%;
size-adjust: 109%;
}}
.key {{fill: {theme['key']};}}
.value {{fill: {theme['value']};}}
.addColor {{fill: {theme['add']};}}
.delColor {{fill: {theme['delc']};}}
.cc {{fill: {theme['cc']};}}
text, tspan {{white-space: pre;}}
</style>""",
        f'<rect width="{width}" height="{height}" fill="{theme["bg"]}" rx="15"/>',
    ]

    # ---- Typewriter intro: "nathan@bijo:~$ neofetch" + blinking cursor ----
    # The typed command is ONE static, fully-opaque text run — visibility is
    # controlled by a clip-path rect growing in discrete steps, not by
    # toggling opacity on individual <tspan> characters. That per-character
    # approach was tested and dropped: at least one real SVG renderer
    # (resvg) silently ignores `opacity` set on <tspan>, confirmed by
    # inspecting the raw output bytes, not just eyeballing a render. A
    # clip-path's rect `width` is a basic numeric attribute animation with
    # no such ambiguity, so the reveal can't silently fail to hide text.
    prompt = FIELDS[0][0] + ":~$ "
    p.append(f'<text x="{ART_X}" y="{TOP}" fill="{theme["art"]}" font-size="{FONT_SIZE}px">')
    cx = _emit_segments(p, ART_X, TOP, [(prompt, None, len(prompt))])
    cmd_start_x = cx
    cmd_width = len(INTRO_CMD) * CHAR_W
    p.append("</text>")

    type_dur = len(INTRO_CMD) * CHAR_DELAY
    step_widths = [i * CHAR_W for i in range(len(INTRO_CMD) + 1)]
    key_times = [i / len(INTRO_CMD) for i in range(len(INTRO_CMD) + 1)]
    clip_id = f"typeClip-{theme_name}"
    p.append(
        f'<clipPath id="{clip_id}"><rect x="{cmd_start_x:.1f}" y="{TOP - FONT_SIZE}" '
        f'width="0" height="{FONT_SIZE + 6}">'
        f'<animate attributeName="width" begin="{TYPE_START:.2f}s" dur="{type_dur:.2f}s" '
        f'calcMode="discrete" fill="freeze" '
        f'keyTimes="{";".join(f"{k:.4f}" for k in key_times)}" '
        f'values="{";".join(f"{v:.1f}" for v in step_widths)}"/>'
        f'</rect></clipPath>'
    )
    p.append(f'<g clip-path="url(#{clip_id})">')
    p.append(
        f'<text x="{cmd_start_x:.1f}" y="{TOP}" fill="{theme["art"]}" font-size="{FONT_SIZE}px">'
        f'<tspan x="{cmd_start_x:.1f}" y="{TOP}" textLength="{cmd_width:.1f}" '
        f'lengthAdjust="spacingAndGlyphs">{escape(INTRO_CMD)}</tspan></text>'
    )
    p.append("</g>")

    type_end = TYPE_START + type_dur
    reveal_start = type_end + ENTER_PAUSE
    cursor_positions = [cmd_start_x + w for w in step_widths]
    p.append(
        f'<rect x="{cursor_positions[0]:.1f}" y="{TOP - FONT_SIZE + 2}" '
        f'width="{CHAR_W - 1:.1f}" height="{FONT_SIZE + 2}" fill="{theme["art"]}">'
        f'<animate attributeName="x" begin="{TYPE_START:.2f}s" dur="{type_dur:.2f}s" '
        f'calcMode="discrete" fill="freeze" '
        f'keyTimes="{";".join(f"{k:.4f}" for k in key_times)}" '
        f'values="{";".join(f"{v:.1f}" for v in cursor_positions)}"/>'
        f'<animate attributeName="opacity" values="1;1;0;0" keyTimes="0;0.5;0.5;1" '
        f'dur="0.9s" repeatCount="indefinite" begin="0s"/>'
        f'<set attributeName="display" to="none" begin="{reveal_start:.2f}s" fill="freeze"/>'
        f'</rect>'
    )

    # ---- Card content, hidden until the "Enter" pause finishes ----
    p.append(f'<g opacity="0">')
    p.append(
        f'<animate attributeName="opacity" from="0" to="1" '
        f'begin="{reveal_start:.2f}s" dur="{FADE_DUR}s" fill="freeze"/>'
    )

    p.append(f'<text x="{ART_X}" y="{art_top:.1f}" fill="{theme["art"]}" font-size="{art_font:.2f}px" class="ascii">')
    for i, line in enumerate(art_lines):
        tl = len(line) * art_char_w
        p.append(
            f'<tspan x="{ART_X}" y="{art_top + i * art_line_h:.1f}" '
            f'textLength="{tl:.1f}" lengthAdjust="spacingAndGlyphs">{escape(line)}</tspan>'
        )
    p.append("</text>")

    p.append(f'<text x="{col_x}" y="{stats_top:.1f}" fill="{theme["art"]}" font-size="{FONT_SIZE}px">')
    y = stats_top
    for header, rows in FIELDS:
        rule = "-" + "\u2014" * 44 + "-\u2014-"
        header_tl = len(header) * CHAR_W
        p.append(
            f'<tspan x="{col_x:.1f}" y="{y:.1f}" textLength="{header_tl:.1f}" '
            f'lengthAdjust="spacingAndGlyphs">{escape(header)}</tspan> {rule}'
        )
        y += LINE_H
        for row in rows:
            if row is None:
                p.append(f'<tspan x="{col_x:.1f}" y="{y:.1f}" class="cc">. </tspan>')
                y += LINE_H
                continue

            if isinstance(row, list):
                # Compact line: ". label1: ...dots... value1 | label2: ...dots... value2"
                cx = col_x
                cx = _emit_segments(p, cx, y, [(". ", "cc", 2)])
                for j, (label, value) in enumerate(row):
                    value = _resolve(value, stats)
                    fill = dotted(label, value, half_cols)
                    segs = _label_segments(label) + [
                        (":", "cc", 1), (fill, "cc", len(fill)), (value, "value", len(value)),
                    ]
                    cx = _emit_segments(p, cx, y, segs)
                    if j == 0:
                        cx = _emit_segments(p, cx, y, [(SEP, "cc", len(SEP))])
                y += LINE_H
                continue

            label, value = row
            value = _resolve(value, stats)
            fill = dotted(label, value, stats_cols)
            segs = (
                [(". ", "cc", 2)] + _label_segments(label)
                + [(":", "cc", 1), (fill, "cc", len(fill)), (value, "value", len(value))]
            )
            _emit_segments(p, col_x, y, segs)
            y += LINE_H
        y += LINE_H
    p.append("</text>")
    p.append("</g>")
    p.append("</svg>")
    return "\n".join(p), width, height


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--theme", choices=["dark", "light", "both"], default="both")
    ap.add_argument("--live", action="store_true")
    args = ap.parse_args()

    stats = dict(PLACEHOLDER_STATS)
    stats["UPTIME"] = compute_uptime()
    if args.live:
        stats.update(fetch_live_stats(os.environ.get("GH_PAT")))

    check_overflow(stats, compute_stats_cols(stats))

    themes = ["dark", "light"] if args.theme == "both" else [args.theme]
    out_dir = ROOT / "assets"
    out_dir.mkdir(exist_ok=True)
    for t in themes:
        svg, w, h = build(t, stats)
        out_path = out_dir / f"{t}_mode.svg"
        out_path.write_text(svg)
        print(f"wrote {out_path}  ({w}x{h})")


if __name__ == "__main__":
    main()
