#!/usr/bin/env python3
"""
Generates assets/dark_mode.svg and assets/light_mode.svg.

The ASCII portrait is NOT algorithmically generated by this script — it's
read verbatim from assets/ascii-portrait-dark.txt / -light.txt, which are
exact character-grid exports from the user's own ASCII art tool (one span
per character, parsed out of the site's HTML export). Two separate files
are used, not one recolored — the site remaps the density ramp per theme,
so the dark and light grids are genuinely different character data, not
a color swap of the same grid.

Run locally:   python3 scripts/generate_neofetch.py --theme dark
In CI:         python3 scripts/generate_neofetch.py --theme dark --live
"""
import argparse
import os
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
GITHUB_USER = "Nathanbijo"

ART_FILES = {
    "dark": ROOT / "assets" / "ascii-portrait-dark.txt",
    "light": ROOT / "assets" / "ascii-portrait-light.txt",
}

# ---------------------------------------------------------------------------
# Static content
# ---------------------------------------------------------------------------
FIELDS = [
    ("nathan@bijo", [
        ("OS", "Fedora Linux, Android"),
        ("Uptime", "{{UPTIME}}"),
        ("Host", "STEAG Energy Services"),
        ("Kernel", "Simulation Software Engineering Intern"),
        ("IDE", "VS Code, Neovim"),
        None,
        ("Languages.Programming", "Python, TypeScript, Java, SQL"),
        ("Languages.Computer", "HTML, CSS, JSON, LaTeX, YAML"),
        ("Languages.Real", "English, Malayalam, Hindi"),
        None,
        ("Projects.WARESYS", "OCR invoice pipeline, 95% accuracy"),
        ("Projects.MarketFlow", "URL to branded social posts"),
        ("Projects.Padosi", "Neighbourhood ranking [WIP]"),
        None,
        ("Honors", "Cryptography, Neurobots Finalist @ IIT Palakkad"),
    ]),
    ("- Contact", [
        ("Email.Personal", "nathan.bijo@gmail.com"),
        ("LinkedIn", "nathan-bijo"),
        ("GitHub", GITHUB_USER),
        ("Portfolio", "nathanbijo.dev"),
    ]),
    ("- GitHub Stats", [
        ("Repos", "{{REPOS}}"),
        ("Stars", "{{STARS}}"),
        ("Commits", "{{COMMITS}}"),
        ("Followers", "{{FOLLOWERS}}"),
    ]),
]

PLACEHOLDER_STATS = {
    "REPOS": "\u2014", "STARS": "\u2014", "COMMITS": "\u2014", "FOLLOWERS": "\u2014",
    "UPTIME": "\u2014 (set START_DATE below)",
}
START_DATE = None  # e.g. "2022-07-01" — decide what "Uptime" measures for you

# Colors taken literally from the two HTML exports — not restyled.
THEMES = {
    "dark": dict(bg="#000000", art="#ffffff", key="#ffa657", value="#a5d6ff",
                 cc="#8b949e", add="#3fb950", delc="#f85149"),
    "light": dict(bg="#ffffff", art="#000000", key="#9a6700", value="#0550ae",
                  cc="#57606a", add="#1a7f37", delc="#cf222e"),
}

# ---------------------------------------------------------------------------
# Geometry — derived from measuring the reference repo's own layout
# (COL_X - ART_X = 375px for a 44-col grid  =>  ~8.5px/char at font-size 16),
# then recomputed here for an 80-col grid instead of hardcoded.
# ---------------------------------------------------------------------------
FONT_SIZE = 16
CHAR_W = 8.5
LINE_H = 20
ART_X = 15
TOP = 30
GAP = 20          # gutter between art column and stats column
RIGHT_PAD = 25
STATS_COLS = 58   # width budget (chars) for the longest "label: value" line


def compute_uptime():
    if not START_DATE:
        return PLACEHOLDER_STATS["UPTIME"]
    from datetime import date
    y, m, d = map(int, START_DATE.split("-"))
    start = date(y, m, d)
    today = date.today()
    years = today.year - start.year - ((today.month, today.day) < (start.month, start.day))
    months = (today.month - start.month) % 12
    days = (today - date(today.year, today.month, min(start.day, 28))).days % 30
    return f"{years} years, {months} months, {days} days"


def fetch_live_stats(token=None):
    import json
    import urllib.request
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    def get(url):
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.load(r)

    user = get(f"https://api.github.com/users/{GITHUB_USER}")
    repos = get(f"https://api.github.com/users/{GITHUB_USER}/repos?per_page=100")
    stars = sum(r.get("stargazers_count", 0) for r in repos) if isinstance(repos, list) else 0
    return {
        "REPOS": str(user.get("public_repos", "\u2014")),
        "STARS": str(stars),
        "FOLLOWERS": str(user.get("followers", "\u2014")),
        "COMMITS": PLACEHOLDER_STATS["COMMITS"],  # needs GraphQL + PAT
    }


def dotted(label, value, width=STATS_COLS):
    used = len(label) + 1 + len(value) + 2
    n = max(1, width - used)
    return " " + "." * n + " "


def check_overflow(stats):
    """Raise loudly instead of silently emitting a broken SVG."""
    problems = []
    for _, rows in FIELDS:
        for row in rows:
            if row is None:
                continue
            label, value = row
            for k in ("REPOS", "STARS", "COMMITS", "FOLLOWERS", "UPTIME"):
                value = value.replace("{{%s}}" % k, stats[k])
            used = len(label) + 1 + len(value) + 2
            if used > STATS_COLS:
                problems.append(f"{label!r} -> {used}/{STATS_COLS} cols")
    if problems:
        raise ValueError("Field(s) overflow the stats column:\n  " + "\n  ".join(problems))


def build(theme_name, stats):
    theme = THEMES[theme_name]
    art_lines = ART_FILES[theme_name].read_text().split("\n")
    art_cols = max(len(l) for l in art_lines)
    art_rows = len(art_lines)

    col_x = ART_X + art_cols * CHAR_W + GAP
    stats_rows = sum(len(rows) + 1 for _, rows in FIELDS) + len(FIELDS)
    width = int(col_x + STATS_COLS * CHAR_W + RIGHT_PAD)
    height = int(TOP + max(art_rows * LINE_H, stats_rows * LINE_H) + 20)

    font_stack = (
        "ConsolasFallback,Consolas,Menlo,'DejaVu Sans Mono',"
        "'Liberation Mono','Courier New',monospace"
    )

    p = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="0 0 {width} {height}" width="{width}" height="{height}" '
        f'font-family="{font_stack}" font-size="{FONT_SIZE}px">',
        f"""<style>
@font-face {{
src: local('Consolas'), local('Consolas Bold');
font-family: 'ConsolasFallback';
font-display: swap;
-webkit-size-adjust: 109%;
size-adjust: 109%;
}}
.key {{fill: {theme['key']};}}
.value {{fill: {theme['value']};}}
.addColor {{fill: {theme['add']};}}
.delColor {{fill: {theme['delc']};}}
.cc {{fill: {theme['cc']};}}
text, tspan {{white-space: pre;}}
</style>""",
        f'<rect width="{width}" height="{height}" fill="{theme["bg"]}" rx="15"/>',
    ]

    # font-size is set explicitly on each <text> (not just inherited from the
    # <svg> root) since inheritance of presentation-attribute font-size onto
    # nested text is inconsistently honored across renderers.
    p.append(f'<text x="{ART_X}" y="{TOP}" fill="{theme["art"]}" font-size="{FONT_SIZE}px" class="ascii">')
    for i, line in enumerate(art_lines):
        tl = len(line) * CHAR_W
        p.append(
            f'<tspan x="{ART_X}" y="{TOP + i * LINE_H}" '
            f'textLength="{tl:.1f}" lengthAdjust="spacingAndGlyphs">{escape(line)}</tspan>'
        )
    p.append("</text>")

    p.append(f'<text x="{col_x}" y="{TOP}" fill="{theme["art"]}" font-size="{FONT_SIZE}px">')
    y = TOP
    for header, rows in FIELDS:
        rule = "-" + "\u2014" * 44 + "-\u2014-"
        header_tl = len(header) * CHAR_W
        p.append(
            f'<tspan x="{col_x}" y="{y}" textLength="{header_tl:.1f}" '
            f'lengthAdjust="spacingAndGlyphs">{escape(header)}</tspan> {rule}'
        )
        y += LINE_H
        for row in rows:
            if row is None:
                p.append(f'<tspan x="{col_x}" y="{y}" class="cc">. </tspan>')
                y += LINE_H
                continue
            label, value = row
            for k in ("REPOS", "STARS", "COMMITS", "FOLLOWERS", "UPTIME"):
                value = value.replace("{{%s}}" % k, stats[k])
            fill = dotted(label, value)

            # Every segment is a SIBLING tspan with its own explicit x and
            # its own textLength — never nested inside another
            # textLength-controlled tspan. Positions are computed from the
            # fixed design width (CHAR_W), not from where the previous
            # sibling actually finished rendering, so nothing accumulates
            # drift and nothing depends on cascading textLength into
            # children (which is the part that isn't reliable).
            cx = col_x
            segs = [(". ", "cc", 2)]
            for i, part in enumerate(label.split(".")):
                if i:
                    segs.append((".", "key", 1))
                segs.append((part, "key", len(part)))
            segs.append((":", "cc", 1))
            segs.append((fill, "cc", len(fill)))
            segs.append((value, "value", len(value)))

            for text, cls, chars in segs:
                if not text:
                    continue
                w = chars * CHAR_W
                p.append(
                    f'<tspan x="{cx:.1f}" y="{y}" class="{cls}" '
                    f'textLength="{w:.1f}" lengthAdjust="spacingAndGlyphs">{escape(text)}</tspan>'
                )
                cx += w
            y += LINE_H
        y += LINE_H
    p.append("</text></svg>")
    return "\n".join(p), width, height


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--theme", choices=["dark", "light", "both"], default="both")
    ap.add_argument("--live", action="store_true")
    args = ap.parse_args()

    stats = dict(PLACEHOLDER_STATS)
    stats["UPTIME"] = compute_uptime()
    if args.live:
        stats.update(fetch_live_stats(os.environ.get("GH_PAT")))

    check_overflow(stats)

    themes = ["dark", "light"] if args.theme == "both" else [args.theme]
    out_dir = ROOT / "assets"
    out_dir.mkdir(exist_ok=True)
    for t in themes:
        svg, w, h = build(t, stats)
        out_path = out_dir / f"{t}_mode.svg"
        out_path.write_text(svg)
        print(f"wrote {out_path}  ({w}x{h})")


if __name__ == "__main__":
    main()
